return {
        {
                "rebelot/kanagawa.nvim",
                lazy = false,
                priority= 9999,
                config=function ()
                        vim.cmd.colorscheme("carbonfox")
                end
        },
        {
                "ellisonleao/gruvbox.nvim",
        },
        {
                "slugbyte/lackluster.nvim",
        },
        {
                "folke/tokyonight.nvim",
        },
        {
                "rose-pine/neovim",
        },
        {
                "rebelot/kanagawa.nvim",
        },
        {
                "vague2k/vague.nvim",
        },
        {
                "deparr/tairiki.nvim",
        },
        {
                "AlessandroYorba/Alduin",
        },
        {
                "chriskempson/vim-tomorrow-theme",
        },
        {
                "savq/melange-nvim",
        },
        {
                "arcticicestudio/nord-vim",
        },
        {
                "fcpg/vim-fahrenheit",
        },
        {
                "adigitoleo/vim-mellow",
        },
        {
                "Biscuit-Theme/nvim",
        },
        {
                "sample-usr/rakis.nvim",
        },
        {
                "armannikoyan/rusty",
        },
        {
                "EdenEast/nightfox.nvim",
        },
        {
                "nyoom-engineering/oxocarbon.nvim",
        }
}
